# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 19:31
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttype', models.CharField(max_length=140)),
                ('year', models.CharField(max_length=140)),
                ('colour', models.CharField(max_length=140)),
                ('price', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
